#############################################################################
# Makefile for building: SoftPhone
# Generated by qmake (3.1) (Qt 6.4.2)
# Project:  SoftPhone.pro
# Template: app
# Command: /usr/lib/qt6/bin/qmake6 -o Makefile SoftPhone.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -fPIC -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -Wextra -fPIC -D_REENTRANT $(DEFINES)
INCPATH       = -I. -I../../libs/pjproject/pjsip/include -I../../libs/pjproject/pjlib/include -I../../libs/pjproject/pjlib-util/include -I../../libs/pjproject/pjnath/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I. -I. -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++
QMAKE         = /usr/lib/qt6/bin/qmake6
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt6/bin/qmake6 -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt6/bin/qmake6 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = SoftPhone1.0.0
DISTDIR = /home/cejikeme/Codebase/sample_softphone/SoftPhone/.tmp/SoftPhone1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu
LIBS          = $(SUBLIBS) -L/home/cejikeme/Codebase/libs/pjproject/pjsip/lib -lpjsua2 -lpjsua -lpjsip-ua -lpjsip-simple -lpjsip -lpjmedia-codec -lpjmedia-videodev -lpjmedia-audiodev -lpjmedia -lpjnath -lpjlib-util -lpj -lboost_system -lboost_chrono -lboost_thread -ludev -lnetsnmp -lasound -lfftw3 /usr/lib/x86_64-linux-gnu/libQt6Widgets.so /usr/lib/x86_64-linux-gnu/libQt6Gui.so /usr/lib/x86_64-linux-gnu/libGLX.so /usr/lib/x86_64-linux-gnu/libOpenGL.so /usr/lib/x86_64-linux-gnu/libQt6Network.so /usr/lib/x86_64-linux-gnu/libQt6Core.so -lpthread -lGLX -lOpenGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		SoftPhone.cpp \
		FileFactory.cpp \
		FileItem.cpp \
		Functions.cpp \
		IniFileIterator.cpp \
		IniFileLoader.cpp \
		PttAdapter.cpp \
		PttManager.cpp \
		SnmpStack.cpp \
		TCPCommunicator.cpp \
		TransportAdapter.cpp \
		UDPCommunicator.cpp \
		Utility.cpp \
		WavWriter.cpp \
		Plotter.cpp moc_SoftPhone.cpp \
		moc_Plotter.cpp
OBJECTS       = main.o \
		SoftPhone.o \
		FileFactory.o \
		FileItem.o \
		Functions.o \
		IniFileIterator.o \
		IniFileLoader.o \
		PttAdapter.o \
		PttManager.o \
		SnmpStack.o \
		TCPCommunicator.o \
		TransportAdapter.o \
		UDPCommunicator.o \
		Utility.o \
		WavWriter.o \
		Plotter.o \
		moc_SoftPhone.o \
		moc_Plotter.o
DIST          = /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_linguist.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3deffects.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/lex.prf \
		SoftPhone.pro SoftPhone.h \
		Codecs.h \
		ConfigException.h \
		ed137_rtp.h \
		FileFactory.h \
		FileItem.h \
		FileIteratorInterface.h \
		FileLoaderInterface.h \
		IniFileIterator.h \
		IniFileLoader.h \
		IPttListener.h \
		PttAdapter.h \
		PttManager.h \
		SnmpStack.h \
		TCPCommunicator.h \
		TransportAdapter.h \
		UDPCommunicator.h \
		Utility.h \
		WavWriter.h \
		StaticVariables.h \
		Plotter.h main.cpp \
		SoftPhone.cpp \
		FileFactory.cpp \
		FileItem.cpp \
		Functions.cpp \
		IniFileIterator.cpp \
		IniFileLoader.cpp \
		PttAdapter.cpp \
		PttManager.cpp \
		SnmpStack.cpp \
		TCPCommunicator.cpp \
		TransportAdapter.cpp \
		UDPCommunicator.cpp \
		Utility.cpp \
		WavWriter.cpp \
		Plotter.cpp
QMAKE_TARGET  = SoftPhone
DESTDIR       = 
TARGET        = SoftPhone


first: all
####### Build rules

SoftPhone: ui_SoftPhone.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SoftPhone.pro /usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_linguist.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3deffects.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/lex.prf \
		SoftPhone.pro \
		/usr/lib/x86_64-linux-gnu/libQt6Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt6Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt6Network.prl \
		/usr/lib/x86_64-linux-gnu/libQt6Core.prl
	$(QMAKE) -o Makefile SoftPhone.pro
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labsanimation.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labssettings.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labssharedimage.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_linguist.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlcore.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlintegration.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3d.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3d_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dassetutils.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3deffects.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3deffects_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dhelpers.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3diblbaker.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dparticles.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dutils.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quicklayouts.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/lex.prf:
SoftPhone.pro:
/usr/lib/x86_64-linux-gnu/libQt6Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt6Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt6Network.prl:
/usr/lib/x86_64-linux-gnu/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile SoftPhone.pro

qmake_all: FORCE


all: Makefile SoftPhone

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents SoftPhone.h Codecs.h ConfigException.h ed137_rtp.h FileFactory.h FileItem.h FileIteratorInterface.h FileLoaderInterface.h IniFileIterator.h IniFileLoader.h IPttListener.h PttAdapter.h PttManager.h SnmpStack.h TCPCommunicator.h TransportAdapter.h UDPCommunicator.h Utility.h WavWriter.h StaticVariables.h Plotter.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp SoftPhone.cpp FileFactory.cpp FileItem.cpp Functions.cpp IniFileIterator.cpp IniFileLoader.cpp PttAdapter.cpp PttManager.cpp SnmpStack.cpp TCPCommunicator.cpp TransportAdapter.cpp UDPCommunicator.cpp Utility.cpp WavWriter.cpp Plotter.cpp $(DISTDIR)/
	$(COPY_FILE) --parents SoftPhone.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -Wextra -fPIC -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt6/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_SoftPhone.cpp moc_Plotter.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_SoftPhone.cpp moc_Plotter.cpp
moc_SoftPhone.cpp: SoftPhone.h \
		../../libs/pjproject/pjsip/include/pjsua-lib/pjsua.h \
		../../libs/pjproject/pjsip/include/pjsip.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_types.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_config.h \
		../../libs/pjproject/pjlib/include/pj/types.h \
		../../libs/pjproject/pjlib/include/pj/config.h \
		../../libs/pjproject/pjlib/include/pj/compat/cc_msvc.h \
		../../libs/pjproject/pjlib/include/pj/compat/cc_clang.h \
		../../libs/pjproject/pjlib/include/pj/compat/cc_gcc.h \
		../../libs/pjproject/pjlib/include/pj/compat/cc_mwcc.h \
		../../libs/pjproject/pjlib/include/pj/compat/cc_codew.h \
		../../libs/pjproject/pjlib/include/pj/compat/cc_gcce.h \
		../../libs/pjproject/pjlib/include/pj/compat/cc_armcc.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_auto.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_symbian.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_win32_wince.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_winphone8.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_winuwp.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_win32.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_linux.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_palmos.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_sunos.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_darwinos.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_rtems.h \
		../../libs/pjproject/pjlib/include/pj/compat/m_auto.h \
		../../libs/pjproject/pjlib/include/pj/compat/size_t.h \
		../../libs/pjproject/pjlib/include/pj/config_site.h \
		../../libs/pjproject/pjlib/include/pj/limits.h \
		../../libs/pjproject/pjlib/include/pj/compat/limits.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_autoconf.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_errno.h \
		../../libs/pjproject/pjlib/include/pj/errno.h \
		../../libs/pjproject/pjlib/include/pj/compat/errno.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_uri.h \
		../../libs/pjproject/pjlib/include/pj/assert.h \
		../../libs/pjproject/pjlib/include/pj/compat/assert.h \
		../../libs/pjproject/pjlib/include/pj/os.h \
		../../libs/pjproject/pjlib/include/pj/log.h \
		../../libs/pjproject/pjlib/include/pj/list.h \
		../../libs/pjproject/pjlib/include/pj/list_i.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/scanner.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/types.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/config.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/scanner_cis_bitwise.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/scanner_cis_uint.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_tel_uri.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_msg.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_multipart.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_parser.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_event.h \
		../../libs/pjproject/pjlib/include/pj/timer.h \
		../../libs/pjproject/pjlib/include/pj/lock.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_module.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_endpoint.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_transport.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_resolve.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/resolver.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/dns.h \
		../../libs/pjproject/pjlib/include/pj/sock.h \
		../../libs/pjproject/pjlib/include/pj/compat/socket.h \
		../../libs/pjproject/pjlib/include/pj/ioqueue.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_util.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_transport_udp.h \
		../../libs/pjproject/pjlib/include/pj/sock_qos.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_transport_loop.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_transport_tcp.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_transport_tls.h \
		../../libs/pjproject/pjlib/include/pj/pool.h \
		../../libs/pjproject/pjlib/include/pj/pool_alt.h \
		../../libs/pjproject/pjlib/include/pj/pool_i.h \
		../../libs/pjproject/pjlib/include/pj/string.h \
		../../libs/pjproject/pjlib/include/pj/compat/string.h \
		../../libs/pjproject/pjlib/include/pj/compat/stdarg.h \
		../../libs/pjproject/pjlib/include/pj/string_i.h \
		../../libs/pjproject/pjlib/include/pj/ssl_sock.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_auth.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_auth_msg.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_auth_aka.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_auth_parser.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_transaction.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_ua_layer.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_dialog.h \
		../../libs/pjproject/pjsip/include/pjsip_ua.h \
		../../libs/pjproject/pjsip/include/pjsip-ua/sip_inv.h \
		../../libs/pjproject/pjsip/include/pjsip-ua/sip_regc.h \
		../../libs/pjproject/pjsip/include/pjsip-ua/sip_replaces.h \
		../../libs/pjproject/pjsip/include/pjsip-ua/sip_xfer.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/evsub.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/types.h \
		../../libs/pjproject/pjsip/include/pjsip-ua/sip_100rel.h \
		../../libs/pjproject/pjsip/include/pjsip-ua/sip_timer.h \
		../../libs/pjproject/pjsip/include/pjsip-ua/sip_siprec.h \
		../../libs/pjproject/pjsip/include/pjsip_simple.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/dlg_event.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/dialog_info.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/xml.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/evsub_msg.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/iscomposing.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/mwi.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/presence.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/pidf.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/xpidf.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/rpid.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/publish.h \
		../../libs/pjproject/pjnath/include/pjnath.h \
		../../libs/pjproject/pjnath/include/pjnath/config.h \
		../../libs/pjproject/pjnath/include/pjnath/errno.h \
		../../libs/pjproject/pjnath/include/pjnath/ice_session.h \
		../../libs/pjproject/pjnath/include/pjnath/types.h \
		../../libs/pjproject/pjnath/include/pjnath/stun_session.h \
		../../libs/pjproject/pjnath/include/pjnath/stun_msg.h \
		../../libs/pjproject/pjnath/include/pjnath/stun_auth.h \
		../../libs/pjproject/pjnath/include/pjnath/stun_config.h \
		../../libs/pjproject/pjnath/include/pjnath/stun_transaction.h \
		../../libs/pjproject/pjnath/include/pjnath/ice_strans.h \
		../../libs/pjproject/pjnath/include/pjnath/stun_sock.h \
		../../libs/pjproject/pjnath/include/pjnath/turn_sock.h \
		../../libs/pjproject/pjnath/include/pjnath/turn_session.h \
		../../libs/pjproject/pjnath/include/pjnath/nat_detect.h \
		../../libs/pjproject/pjnath/include/pjnath/upnp.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/errno.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/getopt.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/base64.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/crc32.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/hmac_md5.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/md5.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/hmac_sha1.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/sha1.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/srv_resolver.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/dns_server.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/string.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/json.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/stun_simple.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/pcap.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/http_client.h \
		../../libs/pjproject/pjlib/include/pj/activesock.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/cli.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/cli_console.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/cli_imp.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/cli_telnet.h \
		../../libs/pjproject/pjlib/include/pjlib.h \
		../../libs/pjproject/pjlib/include/pj/addr_resolv.h \
		../../libs/pjproject/pjlib/include/pj/argparse.h \
		../../libs/pjproject/pjlib/include/pj/ctype.h \
		../../libs/pjproject/pjlib/include/pj/compat/ctype.h \
		../../libs/pjproject/pjlib/include/pj/array.h \
		../../libs/pjproject/pjlib/include/pj/atomic_queue.h \
		../../libs/pjproject/pjlib/include/pj/except.h \
		../../libs/pjproject/pjlib/include/pj/compat/setjmp.h \
		../../libs/pjproject/pjlib/include/pj/fifobuf.h \
		../../libs/pjproject/pjlib/include/pj/file_access.h \
		../../libs/pjproject/pjlib/include/pj/file_io.h \
		../../libs/pjproject/pjlib/include/pj/guid.h \
		../../libs/pjproject/pjlib/include/pj/hash.h \
		../../libs/pjproject/pjlib/include/pj/ip_helper.h \
		../../libs/pjproject/pjlib/include/pj/math.h \
		../../libs/pjproject/pjlib/include/pj/compat/high_precision.h \
		../../libs/pjproject/pjlib/include/pj/pool_buf.h \
		../../libs/pjproject/pjlib/include/pj/rand.h \
		../../libs/pjproject/pjlib/include/pj/rbtree.h \
		../../libs/pjproject/pjlib/include/pj/sock_select.h \
		../../libs/pjproject/pjlib/include/pj/unicode.h \
		../../libs/pjproject/pjlib/include/pj/unittest.h \
		Utility.h \
		SnmpStack.h \
		TransportAdapter.h \
		../../libs/pjproject/pjsip/include/pjsua.h \
		ed137_rtp.h \
		FileLoaderInterface.h \
		FileIteratorInterface.h \
		FileItem.h \
		ConfigException.h \
		FileFactory.h \
		PttManager.h \
		PttAdapter.h \
		IPttListener.h \
		UDPCommunicator.h \
		TCPCommunicator.h \
		WavWriter.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/cejikeme/Codebase/sample_softphone/SoftPhone/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/cejikeme/Codebase/sample_softphone/SoftPhone -I/home/cejikeme/Codebase/libs/pjproject/pjsip/include -I/home/cejikeme/Codebase/libs/pjproject/pjlib/include -I/home/cejikeme/Codebase/libs/pjproject/pjlib-util/include -I/home/cejikeme/Codebase/libs/pjproject/pjnath/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include SoftPhone.h -o moc_SoftPhone.cpp

moc_Plotter.cpp: Plotter.h \
		moc_predefs.h \
		/usr/lib/qt6/libexec/moc
	/usr/lib/qt6/libexec/moc $(DEFINES) --include /home/cejikeme/Codebase/sample_softphone/SoftPhone/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt6/mkspecs/linux-g++ -I/home/cejikeme/Codebase/sample_softphone/SoftPhone -I/home/cejikeme/Codebase/libs/pjproject/pjsip/include -I/home/cejikeme/Codebase/libs/pjproject/pjlib/include -I/home/cejikeme/Codebase/libs/pjproject/pjlib-util/include -I/home/cejikeme/Codebase/libs/pjproject/pjnath/include -I/usr/include/x86_64-linux-gnu/qt6 -I/usr/include/x86_64-linux-gnu/qt6/QtWidgets -I/usr/include/x86_64-linux-gnu/qt6/QtGui -I/usr/include/x86_64-linux-gnu/qt6/QtNetwork -I/usr/include/x86_64-linux-gnu/qt6/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include Plotter.h -o moc_Plotter.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_SoftPhone.h
compiler_uic_clean:
	-$(DEL_FILE) ui_SoftPhone.h
ui_SoftPhone.h: SoftPhone.ui \
		/usr/lib/qt6/libexec/uic \
		Plotter.h
	/usr/lib/qt6/libexec/uic SoftPhone.ui -o ui_SoftPhone.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp SoftPhone.h \
		../../libs/pjproject/pjsip/include/pjsua-lib/pjsua.h \
		../../libs/pjproject/pjsip/include/pjsip.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_types.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_config.h \
		../../libs/pjproject/pjlib/include/pj/types.h \
		../../libs/pjproject/pjlib/include/pj/config.h \
		../../libs/pjproject/pjlib/include/pj/compat/cc_msvc.h \
		../../libs/pjproject/pjlib/include/pj/compat/cc_clang.h \
		../../libs/pjproject/pjlib/include/pj/compat/cc_gcc.h \
		../../libs/pjproject/pjlib/include/pj/compat/cc_mwcc.h \
		../../libs/pjproject/pjlib/include/pj/compat/cc_codew.h \
		../../libs/pjproject/pjlib/include/pj/compat/cc_gcce.h \
		../../libs/pjproject/pjlib/include/pj/compat/cc_armcc.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_auto.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_symbian.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_win32_wince.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_winphone8.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_winuwp.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_win32.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_linux.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_palmos.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_sunos.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_darwinos.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_rtems.h \
		../../libs/pjproject/pjlib/include/pj/compat/m_auto.h \
		../../libs/pjproject/pjlib/include/pj/compat/size_t.h \
		../../libs/pjproject/pjlib/include/pj/config_site.h \
		../../libs/pjproject/pjlib/include/pj/limits.h \
		../../libs/pjproject/pjlib/include/pj/compat/limits.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_autoconf.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_errno.h \
		../../libs/pjproject/pjlib/include/pj/errno.h \
		../../libs/pjproject/pjlib/include/pj/compat/errno.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_uri.h \
		../../libs/pjproject/pjlib/include/pj/assert.h \
		../../libs/pjproject/pjlib/include/pj/compat/assert.h \
		../../libs/pjproject/pjlib/include/pj/os.h \
		../../libs/pjproject/pjlib/include/pj/log.h \
		../../libs/pjproject/pjlib/include/pj/list.h \
		../../libs/pjproject/pjlib/include/pj/list_i.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/scanner.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/types.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/config.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/scanner_cis_bitwise.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/scanner_cis_uint.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_tel_uri.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_msg.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_multipart.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_parser.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_event.h \
		../../libs/pjproject/pjlib/include/pj/timer.h \
		../../libs/pjproject/pjlib/include/pj/lock.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_module.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_endpoint.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_transport.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_resolve.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/resolver.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/dns.h \
		../../libs/pjproject/pjlib/include/pj/sock.h \
		../../libs/pjproject/pjlib/include/pj/compat/socket.h \
		../../libs/pjproject/pjlib/include/pj/ioqueue.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_util.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_transport_udp.h \
		../../libs/pjproject/pjlib/include/pj/sock_qos.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_transport_loop.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_transport_tcp.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_transport_tls.h \
		../../libs/pjproject/pjlib/include/pj/pool.h \
		../../libs/pjproject/pjlib/include/pj/pool_alt.h \
		../../libs/pjproject/pjlib/include/pj/pool_i.h \
		../../libs/pjproject/pjlib/include/pj/string.h \
		../../libs/pjproject/pjlib/include/pj/compat/string.h \
		../../libs/pjproject/pjlib/include/pj/compat/stdarg.h \
		../../libs/pjproject/pjlib/include/pj/string_i.h \
		../../libs/pjproject/pjlib/include/pj/ssl_sock.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_auth.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_auth_msg.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_auth_aka.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_auth_parser.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_transaction.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_ua_layer.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_dialog.h \
		../../libs/pjproject/pjsip/include/pjsip_ua.h \
		../../libs/pjproject/pjsip/include/pjsip-ua/sip_inv.h \
		../../libs/pjproject/pjsip/include/pjsip-ua/sip_regc.h \
		../../libs/pjproject/pjsip/include/pjsip-ua/sip_replaces.h \
		../../libs/pjproject/pjsip/include/pjsip-ua/sip_xfer.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/evsub.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/types.h \
		../../libs/pjproject/pjsip/include/pjsip-ua/sip_100rel.h \
		../../libs/pjproject/pjsip/include/pjsip-ua/sip_timer.h \
		../../libs/pjproject/pjsip/include/pjsip-ua/sip_siprec.h \
		../../libs/pjproject/pjsip/include/pjsip_simple.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/dlg_event.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/dialog_info.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/xml.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/evsub_msg.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/iscomposing.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/mwi.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/presence.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/pidf.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/xpidf.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/rpid.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/publish.h \
		../../libs/pjproject/pjnath/include/pjnath.h \
		../../libs/pjproject/pjnath/include/pjnath/config.h \
		../../libs/pjproject/pjnath/include/pjnath/errno.h \
		../../libs/pjproject/pjnath/include/pjnath/ice_session.h \
		../../libs/pjproject/pjnath/include/pjnath/types.h \
		../../libs/pjproject/pjnath/include/pjnath/stun_session.h \
		../../libs/pjproject/pjnath/include/pjnath/stun_msg.h \
		../../libs/pjproject/pjnath/include/pjnath/stun_auth.h \
		../../libs/pjproject/pjnath/include/pjnath/stun_config.h \
		../../libs/pjproject/pjnath/include/pjnath/stun_transaction.h \
		../../libs/pjproject/pjnath/include/pjnath/ice_strans.h \
		../../libs/pjproject/pjnath/include/pjnath/stun_sock.h \
		../../libs/pjproject/pjnath/include/pjnath/turn_sock.h \
		../../libs/pjproject/pjnath/include/pjnath/turn_session.h \
		../../libs/pjproject/pjnath/include/pjnath/nat_detect.h \
		../../libs/pjproject/pjnath/include/pjnath/upnp.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/errno.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/getopt.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/base64.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/crc32.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/hmac_md5.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/md5.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/hmac_sha1.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/sha1.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/srv_resolver.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/dns_server.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/string.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/json.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/stun_simple.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/pcap.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/http_client.h \
		../../libs/pjproject/pjlib/include/pj/activesock.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/cli.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/cli_console.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/cli_imp.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/cli_telnet.h \
		../../libs/pjproject/pjlib/include/pjlib.h \
		../../libs/pjproject/pjlib/include/pj/addr_resolv.h \
		../../libs/pjproject/pjlib/include/pj/argparse.h \
		../../libs/pjproject/pjlib/include/pj/ctype.h \
		../../libs/pjproject/pjlib/include/pj/compat/ctype.h \
		../../libs/pjproject/pjlib/include/pj/array.h \
		../../libs/pjproject/pjlib/include/pj/atomic_queue.h \
		../../libs/pjproject/pjlib/include/pj/except.h \
		../../libs/pjproject/pjlib/include/pj/compat/setjmp.h \
		../../libs/pjproject/pjlib/include/pj/fifobuf.h \
		../../libs/pjproject/pjlib/include/pj/file_access.h \
		../../libs/pjproject/pjlib/include/pj/file_io.h \
		../../libs/pjproject/pjlib/include/pj/guid.h \
		../../libs/pjproject/pjlib/include/pj/hash.h \
		../../libs/pjproject/pjlib/include/pj/ip_helper.h \
		../../libs/pjproject/pjlib/include/pj/math.h \
		../../libs/pjproject/pjlib/include/pj/compat/high_precision.h \
		../../libs/pjproject/pjlib/include/pj/pool_buf.h \
		../../libs/pjproject/pjlib/include/pj/rand.h \
		../../libs/pjproject/pjlib/include/pj/rbtree.h \
		../../libs/pjproject/pjlib/include/pj/sock_select.h \
		../../libs/pjproject/pjlib/include/pj/unicode.h \
		../../libs/pjproject/pjlib/include/pj/unittest.h \
		Utility.h \
		SnmpStack.h \
		TransportAdapter.h \
		../../libs/pjproject/pjsip/include/pjsua.h \
		ed137_rtp.h \
		FileLoaderInterface.h \
		FileIteratorInterface.h \
		FileItem.h \
		ConfigException.h \
		FileFactory.h \
		PttManager.h \
		PttAdapter.h \
		IPttListener.h \
		UDPCommunicator.h \
		TCPCommunicator.h \
		WavWriter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

SoftPhone.o: SoftPhone.cpp SoftPhone.h \
		../../libs/pjproject/pjsip/include/pjsua-lib/pjsua.h \
		../../libs/pjproject/pjsip/include/pjsip.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_types.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_config.h \
		../../libs/pjproject/pjlib/include/pj/types.h \
		../../libs/pjproject/pjlib/include/pj/config.h \
		../../libs/pjproject/pjlib/include/pj/compat/cc_msvc.h \
		../../libs/pjproject/pjlib/include/pj/compat/cc_clang.h \
		../../libs/pjproject/pjlib/include/pj/compat/cc_gcc.h \
		../../libs/pjproject/pjlib/include/pj/compat/cc_mwcc.h \
		../../libs/pjproject/pjlib/include/pj/compat/cc_codew.h \
		../../libs/pjproject/pjlib/include/pj/compat/cc_gcce.h \
		../../libs/pjproject/pjlib/include/pj/compat/cc_armcc.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_auto.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_symbian.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_win32_wince.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_winphone8.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_winuwp.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_win32.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_linux.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_palmos.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_sunos.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_darwinos.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_rtems.h \
		../../libs/pjproject/pjlib/include/pj/compat/m_auto.h \
		../../libs/pjproject/pjlib/include/pj/compat/size_t.h \
		../../libs/pjproject/pjlib/include/pj/config_site.h \
		../../libs/pjproject/pjlib/include/pj/limits.h \
		../../libs/pjproject/pjlib/include/pj/compat/limits.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_autoconf.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_errno.h \
		../../libs/pjproject/pjlib/include/pj/errno.h \
		../../libs/pjproject/pjlib/include/pj/compat/errno.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_uri.h \
		../../libs/pjproject/pjlib/include/pj/assert.h \
		../../libs/pjproject/pjlib/include/pj/compat/assert.h \
		../../libs/pjproject/pjlib/include/pj/os.h \
		../../libs/pjproject/pjlib/include/pj/log.h \
		../../libs/pjproject/pjlib/include/pj/list.h \
		../../libs/pjproject/pjlib/include/pj/list_i.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/scanner.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/types.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/config.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/scanner_cis_bitwise.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/scanner_cis_uint.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_tel_uri.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_msg.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_multipart.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_parser.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_event.h \
		../../libs/pjproject/pjlib/include/pj/timer.h \
		../../libs/pjproject/pjlib/include/pj/lock.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_module.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_endpoint.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_transport.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_resolve.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/resolver.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/dns.h \
		../../libs/pjproject/pjlib/include/pj/sock.h \
		../../libs/pjproject/pjlib/include/pj/compat/socket.h \
		../../libs/pjproject/pjlib/include/pj/ioqueue.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_util.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_transport_udp.h \
		../../libs/pjproject/pjlib/include/pj/sock_qos.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_transport_loop.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_transport_tcp.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_transport_tls.h \
		../../libs/pjproject/pjlib/include/pj/pool.h \
		../../libs/pjproject/pjlib/include/pj/pool_alt.h \
		../../libs/pjproject/pjlib/include/pj/pool_i.h \
		../../libs/pjproject/pjlib/include/pj/string.h \
		../../libs/pjproject/pjlib/include/pj/compat/string.h \
		../../libs/pjproject/pjlib/include/pj/compat/stdarg.h \
		../../libs/pjproject/pjlib/include/pj/string_i.h \
		../../libs/pjproject/pjlib/include/pj/ssl_sock.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_auth.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_auth_msg.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_auth_aka.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_auth_parser.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_transaction.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_ua_layer.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_dialog.h \
		../../libs/pjproject/pjsip/include/pjsip_ua.h \
		../../libs/pjproject/pjsip/include/pjsip-ua/sip_inv.h \
		../../libs/pjproject/pjsip/include/pjsip-ua/sip_regc.h \
		../../libs/pjproject/pjsip/include/pjsip-ua/sip_replaces.h \
		../../libs/pjproject/pjsip/include/pjsip-ua/sip_xfer.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/evsub.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/types.h \
		../../libs/pjproject/pjsip/include/pjsip-ua/sip_100rel.h \
		../../libs/pjproject/pjsip/include/pjsip-ua/sip_timer.h \
		../../libs/pjproject/pjsip/include/pjsip-ua/sip_siprec.h \
		../../libs/pjproject/pjsip/include/pjsip_simple.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/dlg_event.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/dialog_info.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/xml.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/evsub_msg.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/iscomposing.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/mwi.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/presence.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/pidf.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/xpidf.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/rpid.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/publish.h \
		../../libs/pjproject/pjnath/include/pjnath.h \
		../../libs/pjproject/pjnath/include/pjnath/config.h \
		../../libs/pjproject/pjnath/include/pjnath/errno.h \
		../../libs/pjproject/pjnath/include/pjnath/ice_session.h \
		../../libs/pjproject/pjnath/include/pjnath/types.h \
		../../libs/pjproject/pjnath/include/pjnath/stun_session.h \
		../../libs/pjproject/pjnath/include/pjnath/stun_msg.h \
		../../libs/pjproject/pjnath/include/pjnath/stun_auth.h \
		../../libs/pjproject/pjnath/include/pjnath/stun_config.h \
		../../libs/pjproject/pjnath/include/pjnath/stun_transaction.h \
		../../libs/pjproject/pjnath/include/pjnath/ice_strans.h \
		../../libs/pjproject/pjnath/include/pjnath/stun_sock.h \
		../../libs/pjproject/pjnath/include/pjnath/turn_sock.h \
		../../libs/pjproject/pjnath/include/pjnath/turn_session.h \
		../../libs/pjproject/pjnath/include/pjnath/nat_detect.h \
		../../libs/pjproject/pjnath/include/pjnath/upnp.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/errno.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/getopt.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/base64.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/crc32.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/hmac_md5.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/md5.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/hmac_sha1.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/sha1.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/srv_resolver.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/dns_server.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/string.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/json.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/stun_simple.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/pcap.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/http_client.h \
		../../libs/pjproject/pjlib/include/pj/activesock.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/cli.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/cli_console.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/cli_imp.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/cli_telnet.h \
		../../libs/pjproject/pjlib/include/pjlib.h \
		../../libs/pjproject/pjlib/include/pj/addr_resolv.h \
		../../libs/pjproject/pjlib/include/pj/argparse.h \
		../../libs/pjproject/pjlib/include/pj/ctype.h \
		../../libs/pjproject/pjlib/include/pj/compat/ctype.h \
		../../libs/pjproject/pjlib/include/pj/array.h \
		../../libs/pjproject/pjlib/include/pj/atomic_queue.h \
		../../libs/pjproject/pjlib/include/pj/except.h \
		../../libs/pjproject/pjlib/include/pj/compat/setjmp.h \
		../../libs/pjproject/pjlib/include/pj/fifobuf.h \
		../../libs/pjproject/pjlib/include/pj/file_access.h \
		../../libs/pjproject/pjlib/include/pj/file_io.h \
		../../libs/pjproject/pjlib/include/pj/guid.h \
		../../libs/pjproject/pjlib/include/pj/hash.h \
		../../libs/pjproject/pjlib/include/pj/ip_helper.h \
		../../libs/pjproject/pjlib/include/pj/math.h \
		../../libs/pjproject/pjlib/include/pj/compat/high_precision.h \
		../../libs/pjproject/pjlib/include/pj/pool_buf.h \
		../../libs/pjproject/pjlib/include/pj/rand.h \
		../../libs/pjproject/pjlib/include/pj/rbtree.h \
		../../libs/pjproject/pjlib/include/pj/sock_select.h \
		../../libs/pjproject/pjlib/include/pj/unicode.h \
		../../libs/pjproject/pjlib/include/pj/unittest.h \
		Utility.h \
		SnmpStack.h \
		TransportAdapter.h \
		../../libs/pjproject/pjsip/include/pjsua.h \
		ed137_rtp.h \
		FileLoaderInterface.h \
		FileIteratorInterface.h \
		FileItem.h \
		ConfigException.h \
		FileFactory.h \
		PttManager.h \
		PttAdapter.h \
		IPttListener.h \
		UDPCommunicator.h \
		TCPCommunicator.h \
		WavWriter.h \
		ui_SoftPhone.h \
		StaticVariables.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SoftPhone.o SoftPhone.cpp

FileFactory.o: FileFactory.cpp FileFactory.h \
		FileLoaderInterface.h \
		FileIteratorInterface.h \
		FileItem.h \
		ConfigException.h \
		IniFileLoader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FileFactory.o FileFactory.cpp

FileItem.o: FileItem.cpp FileItem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FileItem.o FileItem.cpp

Functions.o: Functions.cpp SoftPhone.h \
		../../libs/pjproject/pjsip/include/pjsua-lib/pjsua.h \
		../../libs/pjproject/pjsip/include/pjsip.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_types.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_config.h \
		../../libs/pjproject/pjlib/include/pj/types.h \
		../../libs/pjproject/pjlib/include/pj/config.h \
		../../libs/pjproject/pjlib/include/pj/compat/cc_msvc.h \
		../../libs/pjproject/pjlib/include/pj/compat/cc_clang.h \
		../../libs/pjproject/pjlib/include/pj/compat/cc_gcc.h \
		../../libs/pjproject/pjlib/include/pj/compat/cc_mwcc.h \
		../../libs/pjproject/pjlib/include/pj/compat/cc_codew.h \
		../../libs/pjproject/pjlib/include/pj/compat/cc_gcce.h \
		../../libs/pjproject/pjlib/include/pj/compat/cc_armcc.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_auto.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_symbian.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_win32_wince.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_winphone8.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_winuwp.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_win32.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_linux.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_palmos.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_sunos.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_darwinos.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_rtems.h \
		../../libs/pjproject/pjlib/include/pj/compat/m_auto.h \
		../../libs/pjproject/pjlib/include/pj/compat/size_t.h \
		../../libs/pjproject/pjlib/include/pj/config_site.h \
		../../libs/pjproject/pjlib/include/pj/limits.h \
		../../libs/pjproject/pjlib/include/pj/compat/limits.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_autoconf.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_errno.h \
		../../libs/pjproject/pjlib/include/pj/errno.h \
		../../libs/pjproject/pjlib/include/pj/compat/errno.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_uri.h \
		../../libs/pjproject/pjlib/include/pj/assert.h \
		../../libs/pjproject/pjlib/include/pj/compat/assert.h \
		../../libs/pjproject/pjlib/include/pj/os.h \
		../../libs/pjproject/pjlib/include/pj/log.h \
		../../libs/pjproject/pjlib/include/pj/list.h \
		../../libs/pjproject/pjlib/include/pj/list_i.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/scanner.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/types.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/config.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/scanner_cis_bitwise.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/scanner_cis_uint.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_tel_uri.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_msg.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_multipart.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_parser.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_event.h \
		../../libs/pjproject/pjlib/include/pj/timer.h \
		../../libs/pjproject/pjlib/include/pj/lock.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_module.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_endpoint.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_transport.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_resolve.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/resolver.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/dns.h \
		../../libs/pjproject/pjlib/include/pj/sock.h \
		../../libs/pjproject/pjlib/include/pj/compat/socket.h \
		../../libs/pjproject/pjlib/include/pj/ioqueue.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_util.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_transport_udp.h \
		../../libs/pjproject/pjlib/include/pj/sock_qos.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_transport_loop.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_transport_tcp.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_transport_tls.h \
		../../libs/pjproject/pjlib/include/pj/pool.h \
		../../libs/pjproject/pjlib/include/pj/pool_alt.h \
		../../libs/pjproject/pjlib/include/pj/pool_i.h \
		../../libs/pjproject/pjlib/include/pj/string.h \
		../../libs/pjproject/pjlib/include/pj/compat/string.h \
		../../libs/pjproject/pjlib/include/pj/compat/stdarg.h \
		../../libs/pjproject/pjlib/include/pj/string_i.h \
		../../libs/pjproject/pjlib/include/pj/ssl_sock.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_auth.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_auth_msg.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_auth_aka.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_auth_parser.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_transaction.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_ua_layer.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_dialog.h \
		../../libs/pjproject/pjsip/include/pjsip_ua.h \
		../../libs/pjproject/pjsip/include/pjsip-ua/sip_inv.h \
		../../libs/pjproject/pjsip/include/pjsip-ua/sip_regc.h \
		../../libs/pjproject/pjsip/include/pjsip-ua/sip_replaces.h \
		../../libs/pjproject/pjsip/include/pjsip-ua/sip_xfer.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/evsub.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/types.h \
		../../libs/pjproject/pjsip/include/pjsip-ua/sip_100rel.h \
		../../libs/pjproject/pjsip/include/pjsip-ua/sip_timer.h \
		../../libs/pjproject/pjsip/include/pjsip-ua/sip_siprec.h \
		../../libs/pjproject/pjsip/include/pjsip_simple.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/dlg_event.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/dialog_info.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/xml.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/evsub_msg.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/iscomposing.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/mwi.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/presence.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/pidf.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/xpidf.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/rpid.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/publish.h \
		../../libs/pjproject/pjnath/include/pjnath.h \
		../../libs/pjproject/pjnath/include/pjnath/config.h \
		../../libs/pjproject/pjnath/include/pjnath/errno.h \
		../../libs/pjproject/pjnath/include/pjnath/ice_session.h \
		../../libs/pjproject/pjnath/include/pjnath/types.h \
		../../libs/pjproject/pjnath/include/pjnath/stun_session.h \
		../../libs/pjproject/pjnath/include/pjnath/stun_msg.h \
		../../libs/pjproject/pjnath/include/pjnath/stun_auth.h \
		../../libs/pjproject/pjnath/include/pjnath/stun_config.h \
		../../libs/pjproject/pjnath/include/pjnath/stun_transaction.h \
		../../libs/pjproject/pjnath/include/pjnath/ice_strans.h \
		../../libs/pjproject/pjnath/include/pjnath/stun_sock.h \
		../../libs/pjproject/pjnath/include/pjnath/turn_sock.h \
		../../libs/pjproject/pjnath/include/pjnath/turn_session.h \
		../../libs/pjproject/pjnath/include/pjnath/nat_detect.h \
		../../libs/pjproject/pjnath/include/pjnath/upnp.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/errno.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/getopt.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/base64.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/crc32.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/hmac_md5.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/md5.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/hmac_sha1.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/sha1.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/srv_resolver.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/dns_server.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/string.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/json.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/stun_simple.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/pcap.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/http_client.h \
		../../libs/pjproject/pjlib/include/pj/activesock.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/cli.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/cli_console.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/cli_imp.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/cli_telnet.h \
		../../libs/pjproject/pjlib/include/pjlib.h \
		../../libs/pjproject/pjlib/include/pj/addr_resolv.h \
		../../libs/pjproject/pjlib/include/pj/argparse.h \
		../../libs/pjproject/pjlib/include/pj/ctype.h \
		../../libs/pjproject/pjlib/include/pj/compat/ctype.h \
		../../libs/pjproject/pjlib/include/pj/array.h \
		../../libs/pjproject/pjlib/include/pj/atomic_queue.h \
		../../libs/pjproject/pjlib/include/pj/except.h \
		../../libs/pjproject/pjlib/include/pj/compat/setjmp.h \
		../../libs/pjproject/pjlib/include/pj/fifobuf.h \
		../../libs/pjproject/pjlib/include/pj/file_access.h \
		../../libs/pjproject/pjlib/include/pj/file_io.h \
		../../libs/pjproject/pjlib/include/pj/guid.h \
		../../libs/pjproject/pjlib/include/pj/hash.h \
		../../libs/pjproject/pjlib/include/pj/ip_helper.h \
		../../libs/pjproject/pjlib/include/pj/math.h \
		../../libs/pjproject/pjlib/include/pj/compat/high_precision.h \
		../../libs/pjproject/pjlib/include/pj/pool_buf.h \
		../../libs/pjproject/pjlib/include/pj/rand.h \
		../../libs/pjproject/pjlib/include/pj/rbtree.h \
		../../libs/pjproject/pjlib/include/pj/sock_select.h \
		../../libs/pjproject/pjlib/include/pj/unicode.h \
		../../libs/pjproject/pjlib/include/pj/unittest.h \
		Utility.h \
		SnmpStack.h \
		TransportAdapter.h \
		../../libs/pjproject/pjsip/include/pjsua.h \
		ed137_rtp.h \
		FileLoaderInterface.h \
		FileIteratorInterface.h \
		FileItem.h \
		ConfigException.h \
		FileFactory.h \
		PttManager.h \
		PttAdapter.h \
		IPttListener.h \
		UDPCommunicator.h \
		TCPCommunicator.h \
		WavWriter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Functions.o Functions.cpp

IniFileIterator.o: IniFileIterator.cpp IniFileIterator.h \
		FileIteratorInterface.h \
		FileItem.h \
		ConfigException.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o IniFileIterator.o IniFileIterator.cpp

IniFileLoader.o: IniFileLoader.cpp IniFileLoader.h \
		FileLoaderInterface.h \
		FileIteratorInterface.h \
		FileItem.h \
		ConfigException.h \
		IniFileIterator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o IniFileLoader.o IniFileLoader.cpp

PttAdapter.o: PttAdapter.cpp PttAdapter.h \
		IPttListener.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PttAdapter.o PttAdapter.cpp

PttManager.o: PttManager.cpp PttManager.h \
		Utility.h \
		PttAdapter.h \
		IPttListener.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PttManager.o PttManager.cpp

SnmpStack.o: SnmpStack.cpp SnmpStack.h \
		StaticVariables.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SnmpStack.o SnmpStack.cpp

TCPCommunicator.o: TCPCommunicator.cpp TCPCommunicator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TCPCommunicator.o TCPCommunicator.cpp

TransportAdapter.o: TransportAdapter.cpp TransportAdapter.h \
		../../libs/pjproject/pjsip/include/pjsua.h \
		../../libs/pjproject/pjsip/include/pjsua-lib/pjsua.h \
		../../libs/pjproject/pjsip/include/pjsip.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_types.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_config.h \
		../../libs/pjproject/pjlib/include/pj/types.h \
		../../libs/pjproject/pjlib/include/pj/config.h \
		../../libs/pjproject/pjlib/include/pj/compat/cc_msvc.h \
		../../libs/pjproject/pjlib/include/pj/compat/cc_clang.h \
		../../libs/pjproject/pjlib/include/pj/compat/cc_gcc.h \
		../../libs/pjproject/pjlib/include/pj/compat/cc_mwcc.h \
		../../libs/pjproject/pjlib/include/pj/compat/cc_codew.h \
		../../libs/pjproject/pjlib/include/pj/compat/cc_gcce.h \
		../../libs/pjproject/pjlib/include/pj/compat/cc_armcc.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_auto.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_symbian.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_win32_wince.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_winphone8.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_winuwp.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_win32.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_linux.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_palmos.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_sunos.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_darwinos.h \
		../../libs/pjproject/pjlib/include/pj/compat/os_rtems.h \
		../../libs/pjproject/pjlib/include/pj/compat/m_auto.h \
		../../libs/pjproject/pjlib/include/pj/compat/size_t.h \
		../../libs/pjproject/pjlib/include/pj/config_site.h \
		../../libs/pjproject/pjlib/include/pj/limits.h \
		../../libs/pjproject/pjlib/include/pj/compat/limits.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_autoconf.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_errno.h \
		../../libs/pjproject/pjlib/include/pj/errno.h \
		../../libs/pjproject/pjlib/include/pj/compat/errno.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_uri.h \
		../../libs/pjproject/pjlib/include/pj/assert.h \
		../../libs/pjproject/pjlib/include/pj/compat/assert.h \
		../../libs/pjproject/pjlib/include/pj/os.h \
		../../libs/pjproject/pjlib/include/pj/log.h \
		../../libs/pjproject/pjlib/include/pj/list.h \
		../../libs/pjproject/pjlib/include/pj/list_i.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/scanner.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/types.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/config.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/scanner_cis_bitwise.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/scanner_cis_uint.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_tel_uri.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_msg.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_multipart.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_parser.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_event.h \
		../../libs/pjproject/pjlib/include/pj/timer.h \
		../../libs/pjproject/pjlib/include/pj/lock.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_module.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_endpoint.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_transport.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_resolve.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/resolver.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/dns.h \
		../../libs/pjproject/pjlib/include/pj/sock.h \
		../../libs/pjproject/pjlib/include/pj/compat/socket.h \
		../../libs/pjproject/pjlib/include/pj/ioqueue.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_util.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_transport_udp.h \
		../../libs/pjproject/pjlib/include/pj/sock_qos.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_transport_loop.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_transport_tcp.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_transport_tls.h \
		../../libs/pjproject/pjlib/include/pj/pool.h \
		../../libs/pjproject/pjlib/include/pj/pool_alt.h \
		../../libs/pjproject/pjlib/include/pj/pool_i.h \
		../../libs/pjproject/pjlib/include/pj/string.h \
		../../libs/pjproject/pjlib/include/pj/compat/string.h \
		../../libs/pjproject/pjlib/include/pj/compat/stdarg.h \
		../../libs/pjproject/pjlib/include/pj/string_i.h \
		../../libs/pjproject/pjlib/include/pj/ssl_sock.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_auth.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_auth_msg.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_auth_aka.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_auth_parser.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_transaction.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_ua_layer.h \
		../../libs/pjproject/pjsip/include/pjsip/sip_dialog.h \
		../../libs/pjproject/pjsip/include/pjsip_ua.h \
		../../libs/pjproject/pjsip/include/pjsip-ua/sip_inv.h \
		../../libs/pjproject/pjsip/include/pjsip-ua/sip_regc.h \
		../../libs/pjproject/pjsip/include/pjsip-ua/sip_replaces.h \
		../../libs/pjproject/pjsip/include/pjsip-ua/sip_xfer.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/evsub.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/types.h \
		../../libs/pjproject/pjsip/include/pjsip-ua/sip_100rel.h \
		../../libs/pjproject/pjsip/include/pjsip-ua/sip_timer.h \
		../../libs/pjproject/pjsip/include/pjsip-ua/sip_siprec.h \
		../../libs/pjproject/pjsip/include/pjsip_simple.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/dlg_event.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/dialog_info.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/xml.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/evsub_msg.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/iscomposing.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/mwi.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/presence.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/pidf.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/xpidf.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/rpid.h \
		../../libs/pjproject/pjsip/include/pjsip-simple/publish.h \
		../../libs/pjproject/pjnath/include/pjnath.h \
		../../libs/pjproject/pjnath/include/pjnath/config.h \
		../../libs/pjproject/pjnath/include/pjnath/errno.h \
		../../libs/pjproject/pjnath/include/pjnath/ice_session.h \
		../../libs/pjproject/pjnath/include/pjnath/types.h \
		../../libs/pjproject/pjnath/include/pjnath/stun_session.h \
		../../libs/pjproject/pjnath/include/pjnath/stun_msg.h \
		../../libs/pjproject/pjnath/include/pjnath/stun_auth.h \
		../../libs/pjproject/pjnath/include/pjnath/stun_config.h \
		../../libs/pjproject/pjnath/include/pjnath/stun_transaction.h \
		../../libs/pjproject/pjnath/include/pjnath/ice_strans.h \
		../../libs/pjproject/pjnath/include/pjnath/stun_sock.h \
		../../libs/pjproject/pjnath/include/pjnath/turn_sock.h \
		../../libs/pjproject/pjnath/include/pjnath/turn_session.h \
		../../libs/pjproject/pjnath/include/pjnath/nat_detect.h \
		../../libs/pjproject/pjnath/include/pjnath/upnp.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/errno.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/getopt.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/base64.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/crc32.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/hmac_md5.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/md5.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/hmac_sha1.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/sha1.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/srv_resolver.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/dns_server.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/string.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/json.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/stun_simple.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/pcap.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/http_client.h \
		../../libs/pjproject/pjlib/include/pj/activesock.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/cli.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/cli_console.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/cli_imp.h \
		../../libs/pjproject/pjlib-util/include/pjlib-util/cli_telnet.h \
		../../libs/pjproject/pjlib/include/pjlib.h \
		../../libs/pjproject/pjlib/include/pj/addr_resolv.h \
		../../libs/pjproject/pjlib/include/pj/argparse.h \
		../../libs/pjproject/pjlib/include/pj/ctype.h \
		../../libs/pjproject/pjlib/include/pj/compat/ctype.h \
		../../libs/pjproject/pjlib/include/pj/array.h \
		../../libs/pjproject/pjlib/include/pj/atomic_queue.h \
		../../libs/pjproject/pjlib/include/pj/except.h \
		../../libs/pjproject/pjlib/include/pj/compat/setjmp.h \
		../../libs/pjproject/pjlib/include/pj/fifobuf.h \
		../../libs/pjproject/pjlib/include/pj/file_access.h \
		../../libs/pjproject/pjlib/include/pj/file_io.h \
		../../libs/pjproject/pjlib/include/pj/guid.h \
		../../libs/pjproject/pjlib/include/pj/hash.h \
		../../libs/pjproject/pjlib/include/pj/ip_helper.h \
		../../libs/pjproject/pjlib/include/pj/math.h \
		../../libs/pjproject/pjlib/include/pj/compat/high_precision.h \
		../../libs/pjproject/pjlib/include/pj/pool_buf.h \
		../../libs/pjproject/pjlib/include/pj/rand.h \
		../../libs/pjproject/pjlib/include/pj/rbtree.h \
		../../libs/pjproject/pjlib/include/pj/sock_select.h \
		../../libs/pjproject/pjlib/include/pj/unicode.h \
		../../libs/pjproject/pjlib/include/pj/unittest.h \
		ed137_rtp.h \
		SoftPhone.h \
		Utility.h \
		SnmpStack.h \
		FileLoaderInterface.h \
		FileIteratorInterface.h \
		FileItem.h \
		ConfigException.h \
		FileFactory.h \
		PttManager.h \
		PttAdapter.h \
		IPttListener.h \
		UDPCommunicator.h \
		TCPCommunicator.h \
		WavWriter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TransportAdapter.o TransportAdapter.cpp

UDPCommunicator.o: UDPCommunicator.cpp UDPCommunicator.h \
		Utility.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o UDPCommunicator.o UDPCommunicator.cpp

Utility.o: Utility.cpp Utility.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Utility.o Utility.cpp

WavWriter.o: WavWriter.cpp WavWriter.h \
		Codecs.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WavWriter.o WavWriter.cpp

Plotter.o: Plotter.cpp Plotter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Plotter.o Plotter.cpp

moc_SoftPhone.o: moc_SoftPhone.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SoftPhone.o moc_SoftPhone.cpp

moc_Plotter.o: moc_Plotter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Plotter.o moc_Plotter.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

.SUFFIXES:

